version: '2.4'
services:
  db:
    image: postgres:16
    container_name: bookmanager_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bookmanager
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgres_sql/data
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:
